// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/java/com/yue/rip.proto

package com.yue;

public final class Rip {
  private Rip() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface PacketOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Packet)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.Packet.Command command = 1;</code>
     * @return The enum numeric value on the wire for command.
     */
    int getCommandValue();
    /**
     * <code>.Packet.Command command = 1;</code>
     * @return The command.
     */
    com.yue.Rip.Packet.Command getCommand();

    /**
     * <code>int32 routerId = 2;</code>
     * @return The routerId.
     */
    int getRouterId();

    /**
     * <code>repeated .Packet.RouterEntry routerEntries = 3;</code>
     */
    java.util.List<com.yue.Rip.Packet.RouterEntry> 
        getRouterEntriesList();
    /**
     * <code>repeated .Packet.RouterEntry routerEntries = 3;</code>
     */
    com.yue.Rip.Packet.RouterEntry getRouterEntries(int index);
    /**
     * <code>repeated .Packet.RouterEntry routerEntries = 3;</code>
     */
    int getRouterEntriesCount();
    /**
     * <code>repeated .Packet.RouterEntry routerEntries = 3;</code>
     */
    java.util.List<? extends com.yue.Rip.Packet.RouterEntryOrBuilder> 
        getRouterEntriesOrBuilderList();
    /**
     * <code>repeated .Packet.RouterEntry routerEntries = 3;</code>
     */
    com.yue.Rip.Packet.RouterEntryOrBuilder getRouterEntriesOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code Packet}
   */
  public static final class Packet extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Packet)
      PacketOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Packet.newBuilder() to construct.
    private Packet(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Packet() {
      command_ = 0;
      routerEntries_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Packet();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Packet(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              int rawValue = input.readEnum();

              command_ = rawValue;
              break;
            }
            case 16: {

              routerId_ = input.readInt32();
              break;
            }
            case 26: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                routerEntries_ = new java.util.ArrayList<com.yue.Rip.Packet.RouterEntry>();
                mutable_bitField0_ |= 0x00000001;
              }
              routerEntries_.add(
                  input.readMessage(com.yue.Rip.Packet.RouterEntry.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          routerEntries_ = java.util.Collections.unmodifiableList(routerEntries_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.yue.Rip.internal_static_Packet_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.yue.Rip.internal_static_Packet_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.yue.Rip.Packet.class, com.yue.Rip.Packet.Builder.class);
    }

    /**
     * Protobuf enum {@code Packet.Command}
     */
    public enum Command
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>REQUEST = 0;</code>
       */
      REQUEST(0),
      /**
       * <code>RESPONSE = 1;</code>
       */
      RESPONSE(1),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>REQUEST = 0;</code>
       */
      public static final int REQUEST_VALUE = 0;
      /**
       * <code>RESPONSE = 1;</code>
       */
      public static final int RESPONSE_VALUE = 1;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static Command valueOf(int value) {
        return forNumber(value);
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       */
      public static Command forNumber(int value) {
        switch (value) {
          case 0: return REQUEST;
          case 1: return RESPONSE;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Command>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          Command> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Command>() {
              public Command findValueByNumber(int number) {
                return Command.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalStateException(
              "Can't get the descriptor of an unrecognized enum value.");
        }
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.yue.Rip.Packet.getDescriptor().getEnumTypes().get(0);
      }

      private static final Command[] VALUES = values();

      public static Command valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private Command(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:Packet.Command)
    }

    public interface RouterEntryOrBuilder extends
        // @@protoc_insertion_point(interface_extends:Packet.RouterEntry)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>int32 dest = 1;</code>
       * @return The dest.
       */
      int getDest();

      /**
       * <code>int32 nextHop = 2;</code>
       * @return The nextHop.
       */
      int getNextHop();

      /**
       * <code>int32 metric = 3;</code>
       * @return The metric.
       */
      int getMetric();
    }
    /**
     * Protobuf type {@code Packet.RouterEntry}
     */
    public static final class RouterEntry extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:Packet.RouterEntry)
        RouterEntryOrBuilder {
    private static final long serialVersionUID = 0L;
      // Use RouterEntry.newBuilder() to construct.
      private RouterEntry(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private RouterEntry() {
      }

      @java.lang.Override
      @SuppressWarnings({"unused"})
      protected java.lang.Object newInstance(
          UnusedPrivateParameter unused) {
        return new RouterEntry();
      }

      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return this.unknownFields;
      }
      private RouterEntry(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {

                dest_ = input.readInt32();
                break;
              }
              case 16: {

                nextHop_ = input.readInt32();
                break;
              }
              case 24: {

                metric_ = input.readInt32();
                break;
              }
              default: {
                if (!parseUnknownField(
                    input, unknownFields, extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.yue.Rip.internal_static_Packet_RouterEntry_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.yue.Rip.internal_static_Packet_RouterEntry_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.yue.Rip.Packet.RouterEntry.class, com.yue.Rip.Packet.RouterEntry.Builder.class);
      }

      public static final int DEST_FIELD_NUMBER = 1;
      private int dest_;
      /**
       * <code>int32 dest = 1;</code>
       * @return The dest.
       */
      @java.lang.Override
      public int getDest() {
        return dest_;
      }

      public static final int NEXTHOP_FIELD_NUMBER = 2;
      private int nextHop_;
      /**
       * <code>int32 nextHop = 2;</code>
       * @return The nextHop.
       */
      @java.lang.Override
      public int getNextHop() {
        return nextHop_;
      }

      public static final int METRIC_FIELD_NUMBER = 3;
      private int metric_;
      /**
       * <code>int32 metric = 3;</code>
       * @return The metric.
       */
      @java.lang.Override
      public int getMetric() {
        return metric_;
      }

      private byte memoizedIsInitialized = -1;
      @java.lang.Override
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      @java.lang.Override
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (dest_ != 0) {
          output.writeInt32(1, dest_);
        }
        if (nextHop_ != 0) {
          output.writeInt32(2, nextHop_);
        }
        if (metric_ != 0) {
          output.writeInt32(3, metric_);
        }
        unknownFields.writeTo(output);
      }

      @java.lang.Override
      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (dest_ != 0) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(1, dest_);
        }
        if (nextHop_ != 0) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(2, nextHop_);
        }
        if (metric_ != 0) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(3, metric_);
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
      }

      @java.lang.Override
      public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof com.yue.Rip.Packet.RouterEntry)) {
          return super.equals(obj);
        }
        com.yue.Rip.Packet.RouterEntry other = (com.yue.Rip.Packet.RouterEntry) obj;

        if (getDest()
            != other.getDest()) return false;
        if (getNextHop()
            != other.getNextHop()) return false;
        if (getMetric()
            != other.getMetric()) return false;
        if (!unknownFields.equals(other.unknownFields)) return false;
        return true;
      }

      @java.lang.Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        hash = (37 * hash) + DEST_FIELD_NUMBER;
        hash = (53 * hash) + getDest();
        hash = (37 * hash) + NEXTHOP_FIELD_NUMBER;
        hash = (53 * hash) + getNextHop();
        hash = (37 * hash) + METRIC_FIELD_NUMBER;
        hash = (53 * hash) + getMetric();
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static com.yue.Rip.Packet.RouterEntry parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.yue.Rip.Packet.RouterEntry parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.yue.Rip.Packet.RouterEntry parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.yue.Rip.Packet.RouterEntry parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.yue.Rip.Packet.RouterEntry parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.yue.Rip.Packet.RouterEntry parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.yue.Rip.Packet.RouterEntry parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static com.yue.Rip.Packet.RouterEntry parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }
      public static com.yue.Rip.Packet.RouterEntry parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
      }
      public static com.yue.Rip.Packet.RouterEntry parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static com.yue.Rip.Packet.RouterEntry parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static com.yue.Rip.Packet.RouterEntry parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      @java.lang.Override
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(com.yue.Rip.Packet.RouterEntry prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      @java.lang.Override
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code Packet.RouterEntry}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:Packet.RouterEntry)
          com.yue.Rip.Packet.RouterEntryOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return com.yue.Rip.internal_static_Packet_RouterEntry_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return com.yue.Rip.internal_static_Packet_RouterEntry_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  com.yue.Rip.Packet.RouterEntry.class, com.yue.Rip.Packet.RouterEntry.Builder.class);
        }

        // Construct using com.yue.Rip.Packet.RouterEntry.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessageV3
                  .alwaysUseFieldBuilders) {
          }
        }
        @java.lang.Override
        public Builder clear() {
          super.clear();
          dest_ = 0;

          nextHop_ = 0;

          metric_ = 0;

          return this;
        }

        @java.lang.Override
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return com.yue.Rip.internal_static_Packet_RouterEntry_descriptor;
        }

        @java.lang.Override
        public com.yue.Rip.Packet.RouterEntry getDefaultInstanceForType() {
          return com.yue.Rip.Packet.RouterEntry.getDefaultInstance();
        }

        @java.lang.Override
        public com.yue.Rip.Packet.RouterEntry build() {
          com.yue.Rip.Packet.RouterEntry result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        @java.lang.Override
        public com.yue.Rip.Packet.RouterEntry buildPartial() {
          com.yue.Rip.Packet.RouterEntry result = new com.yue.Rip.Packet.RouterEntry(this);
          result.dest_ = dest_;
          result.nextHop_ = nextHop_;
          result.metric_ = metric_;
          onBuilt();
          return result;
        }

        @java.lang.Override
        public Builder clone() {
          return super.clone();
        }
        @java.lang.Override
        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return super.setField(field, value);
        }
        @java.lang.Override
        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
          return super.clearField(field);
        }
        @java.lang.Override
        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
          return super.clearOneof(oneof);
        }
        @java.lang.Override
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, java.lang.Object value) {
          return super.setRepeatedField(field, index, value);
        }
        @java.lang.Override
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return super.addRepeatedField(field, value);
        }
        @java.lang.Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof com.yue.Rip.Packet.RouterEntry) {
            return mergeFrom((com.yue.Rip.Packet.RouterEntry)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(com.yue.Rip.Packet.RouterEntry other) {
          if (other == com.yue.Rip.Packet.RouterEntry.getDefaultInstance()) return this;
          if (other.getDest() != 0) {
            setDest(other.getDest());
          }
          if (other.getNextHop() != 0) {
            setNextHop(other.getNextHop());
          }
          if (other.getMetric() != 0) {
            setMetric(other.getMetric());
          }
          this.mergeUnknownFields(other.unknownFields);
          onChanged();
          return this;
        }

        @java.lang.Override
        public final boolean isInitialized() {
          return true;
        }

        @java.lang.Override
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          com.yue.Rip.Packet.RouterEntry parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (com.yue.Rip.Packet.RouterEntry) e.getUnfinishedMessage();
            throw e.unwrapIOException();
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }

        private int dest_ ;
        /**
         * <code>int32 dest = 1;</code>
         * @return The dest.
         */
        @java.lang.Override
        public int getDest() {
          return dest_;
        }
        /**
         * <code>int32 dest = 1;</code>
         * @param value The dest to set.
         * @return This builder for chaining.
         */
        public Builder setDest(int value) {
          
          dest_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>int32 dest = 1;</code>
         * @return This builder for chaining.
         */
        public Builder clearDest() {
          
          dest_ = 0;
          onChanged();
          return this;
        }

        private int nextHop_ ;
        /**
         * <code>int32 nextHop = 2;</code>
         * @return The nextHop.
         */
        @java.lang.Override
        public int getNextHop() {
          return nextHop_;
        }
        /**
         * <code>int32 nextHop = 2;</code>
         * @param value The nextHop to set.
         * @return This builder for chaining.
         */
        public Builder setNextHop(int value) {
          
          nextHop_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>int32 nextHop = 2;</code>
         * @return This builder for chaining.
         */
        public Builder clearNextHop() {
          
          nextHop_ = 0;
          onChanged();
          return this;
        }

        private int metric_ ;
        /**
         * <code>int32 metric = 3;</code>
         * @return The metric.
         */
        @java.lang.Override
        public int getMetric() {
          return metric_;
        }
        /**
         * <code>int32 metric = 3;</code>
         * @param value The metric to set.
         * @return This builder for chaining.
         */
        public Builder setMetric(int value) {
          
          metric_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>int32 metric = 3;</code>
         * @return This builder for chaining.
         */
        public Builder clearMetric() {
          
          metric_ = 0;
          onChanged();
          return this;
        }
        @java.lang.Override
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.setUnknownFields(unknownFields);
        }

        @java.lang.Override
        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:Packet.RouterEntry)
      }

      // @@protoc_insertion_point(class_scope:Packet.RouterEntry)
      private static final com.yue.Rip.Packet.RouterEntry DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new com.yue.Rip.Packet.RouterEntry();
      }

      public static com.yue.Rip.Packet.RouterEntry getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      private static final com.google.protobuf.Parser<RouterEntry>
          PARSER = new com.google.protobuf.AbstractParser<RouterEntry>() {
        @java.lang.Override
        public RouterEntry parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new RouterEntry(input, extensionRegistry);
        }
      };

      public static com.google.protobuf.Parser<RouterEntry> parser() {
        return PARSER;
      }

      @java.lang.Override
      public com.google.protobuf.Parser<RouterEntry> getParserForType() {
        return PARSER;
      }

      @java.lang.Override
      public com.yue.Rip.Packet.RouterEntry getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    public static final int COMMAND_FIELD_NUMBER = 1;
    private int command_;
    /**
     * <code>.Packet.Command command = 1;</code>
     * @return The enum numeric value on the wire for command.
     */
    @java.lang.Override public int getCommandValue() {
      return command_;
    }
    /**
     * <code>.Packet.Command command = 1;</code>
     * @return The command.
     */
    @java.lang.Override public com.yue.Rip.Packet.Command getCommand() {
      @SuppressWarnings("deprecation")
      com.yue.Rip.Packet.Command result = com.yue.Rip.Packet.Command.valueOf(command_);
      return result == null ? com.yue.Rip.Packet.Command.UNRECOGNIZED : result;
    }

    public static final int ROUTERID_FIELD_NUMBER = 2;
    private int routerId_;
    /**
     * <code>int32 routerId = 2;</code>
     * @return The routerId.
     */
    @java.lang.Override
    public int getRouterId() {
      return routerId_;
    }

    public static final int ROUTERENTRIES_FIELD_NUMBER = 3;
    private java.util.List<com.yue.Rip.Packet.RouterEntry> routerEntries_;
    /**
     * <code>repeated .Packet.RouterEntry routerEntries = 3;</code>
     */
    @java.lang.Override
    public java.util.List<com.yue.Rip.Packet.RouterEntry> getRouterEntriesList() {
      return routerEntries_;
    }
    /**
     * <code>repeated .Packet.RouterEntry routerEntries = 3;</code>
     */
    @java.lang.Override
    public java.util.List<? extends com.yue.Rip.Packet.RouterEntryOrBuilder> 
        getRouterEntriesOrBuilderList() {
      return routerEntries_;
    }
    /**
     * <code>repeated .Packet.RouterEntry routerEntries = 3;</code>
     */
    @java.lang.Override
    public int getRouterEntriesCount() {
      return routerEntries_.size();
    }
    /**
     * <code>repeated .Packet.RouterEntry routerEntries = 3;</code>
     */
    @java.lang.Override
    public com.yue.Rip.Packet.RouterEntry getRouterEntries(int index) {
      return routerEntries_.get(index);
    }
    /**
     * <code>repeated .Packet.RouterEntry routerEntries = 3;</code>
     */
    @java.lang.Override
    public com.yue.Rip.Packet.RouterEntryOrBuilder getRouterEntriesOrBuilder(
        int index) {
      return routerEntries_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (command_ != com.yue.Rip.Packet.Command.REQUEST.getNumber()) {
        output.writeEnum(1, command_);
      }
      if (routerId_ != 0) {
        output.writeInt32(2, routerId_);
      }
      for (int i = 0; i < routerEntries_.size(); i++) {
        output.writeMessage(3, routerEntries_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (command_ != com.yue.Rip.Packet.Command.REQUEST.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, command_);
      }
      if (routerId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, routerId_);
      }
      for (int i = 0; i < routerEntries_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, routerEntries_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.yue.Rip.Packet)) {
        return super.equals(obj);
      }
      com.yue.Rip.Packet other = (com.yue.Rip.Packet) obj;

      if (command_ != other.command_) return false;
      if (getRouterId()
          != other.getRouterId()) return false;
      if (!getRouterEntriesList()
          .equals(other.getRouterEntriesList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + COMMAND_FIELD_NUMBER;
      hash = (53 * hash) + command_;
      hash = (37 * hash) + ROUTERID_FIELD_NUMBER;
      hash = (53 * hash) + getRouterId();
      if (getRouterEntriesCount() > 0) {
        hash = (37 * hash) + ROUTERENTRIES_FIELD_NUMBER;
        hash = (53 * hash) + getRouterEntriesList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.yue.Rip.Packet parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.yue.Rip.Packet parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.yue.Rip.Packet parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.yue.Rip.Packet parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.yue.Rip.Packet parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.yue.Rip.Packet parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.yue.Rip.Packet parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.yue.Rip.Packet parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.yue.Rip.Packet parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.yue.Rip.Packet parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.yue.Rip.Packet parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.yue.Rip.Packet parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.yue.Rip.Packet prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Packet}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Packet)
        com.yue.Rip.PacketOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.yue.Rip.internal_static_Packet_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.yue.Rip.internal_static_Packet_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.yue.Rip.Packet.class, com.yue.Rip.Packet.Builder.class);
      }

      // Construct using com.yue.Rip.Packet.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getRouterEntriesFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        command_ = 0;

        routerId_ = 0;

        if (routerEntriesBuilder_ == null) {
          routerEntries_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          routerEntriesBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.yue.Rip.internal_static_Packet_descriptor;
      }

      @java.lang.Override
      public com.yue.Rip.Packet getDefaultInstanceForType() {
        return com.yue.Rip.Packet.getDefaultInstance();
      }

      @java.lang.Override
      public com.yue.Rip.Packet build() {
        com.yue.Rip.Packet result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.yue.Rip.Packet buildPartial() {
        com.yue.Rip.Packet result = new com.yue.Rip.Packet(this);
        int from_bitField0_ = bitField0_;
        result.command_ = command_;
        result.routerId_ = routerId_;
        if (routerEntriesBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            routerEntries_ = java.util.Collections.unmodifiableList(routerEntries_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.routerEntries_ = routerEntries_;
        } else {
          result.routerEntries_ = routerEntriesBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.yue.Rip.Packet) {
          return mergeFrom((com.yue.Rip.Packet)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.yue.Rip.Packet other) {
        if (other == com.yue.Rip.Packet.getDefaultInstance()) return this;
        if (other.command_ != 0) {
          setCommandValue(other.getCommandValue());
        }
        if (other.getRouterId() != 0) {
          setRouterId(other.getRouterId());
        }
        if (routerEntriesBuilder_ == null) {
          if (!other.routerEntries_.isEmpty()) {
            if (routerEntries_.isEmpty()) {
              routerEntries_ = other.routerEntries_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureRouterEntriesIsMutable();
              routerEntries_.addAll(other.routerEntries_);
            }
            onChanged();
          }
        } else {
          if (!other.routerEntries_.isEmpty()) {
            if (routerEntriesBuilder_.isEmpty()) {
              routerEntriesBuilder_.dispose();
              routerEntriesBuilder_ = null;
              routerEntries_ = other.routerEntries_;
              bitField0_ = (bitField0_ & ~0x00000001);
              routerEntriesBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getRouterEntriesFieldBuilder() : null;
            } else {
              routerEntriesBuilder_.addAllMessages(other.routerEntries_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.yue.Rip.Packet parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.yue.Rip.Packet) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int command_ = 0;
      /**
       * <code>.Packet.Command command = 1;</code>
       * @return The enum numeric value on the wire for command.
       */
      @java.lang.Override public int getCommandValue() {
        return command_;
      }
      /**
       * <code>.Packet.Command command = 1;</code>
       * @param value The enum numeric value on the wire for command to set.
       * @return This builder for chaining.
       */
      public Builder setCommandValue(int value) {
        
        command_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.Packet.Command command = 1;</code>
       * @return The command.
       */
      @java.lang.Override
      public com.yue.Rip.Packet.Command getCommand() {
        @SuppressWarnings("deprecation")
        com.yue.Rip.Packet.Command result = com.yue.Rip.Packet.Command.valueOf(command_);
        return result == null ? com.yue.Rip.Packet.Command.UNRECOGNIZED : result;
      }
      /**
       * <code>.Packet.Command command = 1;</code>
       * @param value The command to set.
       * @return This builder for chaining.
       */
      public Builder setCommand(com.yue.Rip.Packet.Command value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        command_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.Packet.Command command = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearCommand() {
        
        command_ = 0;
        onChanged();
        return this;
      }

      private int routerId_ ;
      /**
       * <code>int32 routerId = 2;</code>
       * @return The routerId.
       */
      @java.lang.Override
      public int getRouterId() {
        return routerId_;
      }
      /**
       * <code>int32 routerId = 2;</code>
       * @param value The routerId to set.
       * @return This builder for chaining.
       */
      public Builder setRouterId(int value) {
        
        routerId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 routerId = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearRouterId() {
        
        routerId_ = 0;
        onChanged();
        return this;
      }

      private java.util.List<com.yue.Rip.Packet.RouterEntry> routerEntries_ =
        java.util.Collections.emptyList();
      private void ensureRouterEntriesIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          routerEntries_ = new java.util.ArrayList<com.yue.Rip.Packet.RouterEntry>(routerEntries_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.yue.Rip.Packet.RouterEntry, com.yue.Rip.Packet.RouterEntry.Builder, com.yue.Rip.Packet.RouterEntryOrBuilder> routerEntriesBuilder_;

      /**
       * <code>repeated .Packet.RouterEntry routerEntries = 3;</code>
       */
      public java.util.List<com.yue.Rip.Packet.RouterEntry> getRouterEntriesList() {
        if (routerEntriesBuilder_ == null) {
          return java.util.Collections.unmodifiableList(routerEntries_);
        } else {
          return routerEntriesBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .Packet.RouterEntry routerEntries = 3;</code>
       */
      public int getRouterEntriesCount() {
        if (routerEntriesBuilder_ == null) {
          return routerEntries_.size();
        } else {
          return routerEntriesBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .Packet.RouterEntry routerEntries = 3;</code>
       */
      public com.yue.Rip.Packet.RouterEntry getRouterEntries(int index) {
        if (routerEntriesBuilder_ == null) {
          return routerEntries_.get(index);
        } else {
          return routerEntriesBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .Packet.RouterEntry routerEntries = 3;</code>
       */
      public Builder setRouterEntries(
          int index, com.yue.Rip.Packet.RouterEntry value) {
        if (routerEntriesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRouterEntriesIsMutable();
          routerEntries_.set(index, value);
          onChanged();
        } else {
          routerEntriesBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Packet.RouterEntry routerEntries = 3;</code>
       */
      public Builder setRouterEntries(
          int index, com.yue.Rip.Packet.RouterEntry.Builder builderForValue) {
        if (routerEntriesBuilder_ == null) {
          ensureRouterEntriesIsMutable();
          routerEntries_.set(index, builderForValue.build());
          onChanged();
        } else {
          routerEntriesBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Packet.RouterEntry routerEntries = 3;</code>
       */
      public Builder addRouterEntries(com.yue.Rip.Packet.RouterEntry value) {
        if (routerEntriesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRouterEntriesIsMutable();
          routerEntries_.add(value);
          onChanged();
        } else {
          routerEntriesBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .Packet.RouterEntry routerEntries = 3;</code>
       */
      public Builder addRouterEntries(
          int index, com.yue.Rip.Packet.RouterEntry value) {
        if (routerEntriesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRouterEntriesIsMutable();
          routerEntries_.add(index, value);
          onChanged();
        } else {
          routerEntriesBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Packet.RouterEntry routerEntries = 3;</code>
       */
      public Builder addRouterEntries(
          com.yue.Rip.Packet.RouterEntry.Builder builderForValue) {
        if (routerEntriesBuilder_ == null) {
          ensureRouterEntriesIsMutable();
          routerEntries_.add(builderForValue.build());
          onChanged();
        } else {
          routerEntriesBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Packet.RouterEntry routerEntries = 3;</code>
       */
      public Builder addRouterEntries(
          int index, com.yue.Rip.Packet.RouterEntry.Builder builderForValue) {
        if (routerEntriesBuilder_ == null) {
          ensureRouterEntriesIsMutable();
          routerEntries_.add(index, builderForValue.build());
          onChanged();
        } else {
          routerEntriesBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Packet.RouterEntry routerEntries = 3;</code>
       */
      public Builder addAllRouterEntries(
          java.lang.Iterable<? extends com.yue.Rip.Packet.RouterEntry> values) {
        if (routerEntriesBuilder_ == null) {
          ensureRouterEntriesIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, routerEntries_);
          onChanged();
        } else {
          routerEntriesBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .Packet.RouterEntry routerEntries = 3;</code>
       */
      public Builder clearRouterEntries() {
        if (routerEntriesBuilder_ == null) {
          routerEntries_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          routerEntriesBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .Packet.RouterEntry routerEntries = 3;</code>
       */
      public Builder removeRouterEntries(int index) {
        if (routerEntriesBuilder_ == null) {
          ensureRouterEntriesIsMutable();
          routerEntries_.remove(index);
          onChanged();
        } else {
          routerEntriesBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .Packet.RouterEntry routerEntries = 3;</code>
       */
      public com.yue.Rip.Packet.RouterEntry.Builder getRouterEntriesBuilder(
          int index) {
        return getRouterEntriesFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .Packet.RouterEntry routerEntries = 3;</code>
       */
      public com.yue.Rip.Packet.RouterEntryOrBuilder getRouterEntriesOrBuilder(
          int index) {
        if (routerEntriesBuilder_ == null) {
          return routerEntries_.get(index);  } else {
          return routerEntriesBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .Packet.RouterEntry routerEntries = 3;</code>
       */
      public java.util.List<? extends com.yue.Rip.Packet.RouterEntryOrBuilder> 
           getRouterEntriesOrBuilderList() {
        if (routerEntriesBuilder_ != null) {
          return routerEntriesBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(routerEntries_);
        }
      }
      /**
       * <code>repeated .Packet.RouterEntry routerEntries = 3;</code>
       */
      public com.yue.Rip.Packet.RouterEntry.Builder addRouterEntriesBuilder() {
        return getRouterEntriesFieldBuilder().addBuilder(
            com.yue.Rip.Packet.RouterEntry.getDefaultInstance());
      }
      /**
       * <code>repeated .Packet.RouterEntry routerEntries = 3;</code>
       */
      public com.yue.Rip.Packet.RouterEntry.Builder addRouterEntriesBuilder(
          int index) {
        return getRouterEntriesFieldBuilder().addBuilder(
            index, com.yue.Rip.Packet.RouterEntry.getDefaultInstance());
      }
      /**
       * <code>repeated .Packet.RouterEntry routerEntries = 3;</code>
       */
      public java.util.List<com.yue.Rip.Packet.RouterEntry.Builder> 
           getRouterEntriesBuilderList() {
        return getRouterEntriesFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.yue.Rip.Packet.RouterEntry, com.yue.Rip.Packet.RouterEntry.Builder, com.yue.Rip.Packet.RouterEntryOrBuilder> 
          getRouterEntriesFieldBuilder() {
        if (routerEntriesBuilder_ == null) {
          routerEntriesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.yue.Rip.Packet.RouterEntry, com.yue.Rip.Packet.RouterEntry.Builder, com.yue.Rip.Packet.RouterEntryOrBuilder>(
                  routerEntries_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          routerEntries_ = null;
        }
        return routerEntriesBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Packet)
    }

    // @@protoc_insertion_point(class_scope:Packet)
    private static final com.yue.Rip.Packet DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.yue.Rip.Packet();
    }

    public static com.yue.Rip.Packet getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Packet>
        PARSER = new com.google.protobuf.AbstractParser<Packet>() {
      @java.lang.Override
      public Packet parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Packet(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Packet> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Packet> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.yue.Rip.Packet getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Packet_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Packet_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Packet_RouterEntry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Packet_RouterEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\037src/main/java/com/yue/rip.proto\"\314\001\n\006Pa" +
      "cket\022 \n\007command\030\001 \001(\0162\017.Packet.Command\022\020" +
      "\n\010routerId\030\002 \001(\005\022*\n\rrouterEntries\030\003 \003(\0132" +
      "\023.Packet.RouterEntry\032<\n\013RouterEntry\022\014\n\004d" +
      "est\030\001 \001(\005\022\017\n\007nextHop\030\002 \001(\005\022\016\n\006metric\030\003 \001" +
      "(\005\"$\n\007Command\022\013\n\007REQUEST\020\000\022\014\n\010RESPONSE\020\001" +
      "B\t\n\007com.yueb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_Packet_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Packet_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Packet_descriptor,
        new java.lang.String[] { "Command", "RouterId", "RouterEntries", });
    internal_static_Packet_RouterEntry_descriptor =
      internal_static_Packet_descriptor.getNestedTypes().get(0);
    internal_static_Packet_RouterEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Packet_RouterEntry_descriptor,
        new java.lang.String[] { "Dest", "NextHop", "Metric", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
